services:
  guesshueapi:
    image: guesshueapi
    build:
      context: .
      dockerfile: GuessHueAPI/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=guesshue;Username=postgres;Password=${DB_PASSWORD}
    depends_on:
      - db
      - guesshuemigrations

  guesshuemigrations:
    image: guesshuemigrations
    build:
      context: .
      dockerfile: GuessHueMigrations/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=guesshue;Username=postgres;Password=${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: guesshue
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1.5s
      timeout: 5s
      retries: 5
      
  seq:
    image: datalust/seq:latest
    container_name: guesshue-seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8081:80"

volumes:
  postgres_data:
